# permissions for end users to view magentoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magento-viewer-role
rules:
- apiGroups:
  - adobe.com.adobe.com
  resources:
  - magentoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - adobe.com.adobe.com
  resources:
  - magentoes/status
  verbs:
  - get
